manifest: something.csv

adaptor_fwd: AGATCGGAAGAGC 
adaptor_rev: AGATCGGAAGAGC

umi_length: 10

barcode_csv: /home/hsher/projects/oligoCLIP/barcode.csv # reverse complemented sequence.

STAR_REP: /projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/star_2_7_homo_sapiens_repbase_fixed_v2
STAR_DIR: /projects/ps-yeolab5/hsher/Tao_circSTAMP/star_2_7_gencode35
