MANIFEST: /home/hsher/projects/oligoCLIP/config/fastq_csv/katie_pe.csv
WORKDIR: /home/hsher/scratch/oligo_PE
adaptor_fwd: AGATCGGAAGAGC 
adaptor_rev: AGATCGGAAGAGC

umi_length: 10

barcode_csv: /home/hsher/projects/oligoCLIP/config/barcode_csv/katie_pe.csv # reverse complemented sequence.

STAR_REP: /projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/star_2_7_homo_sapiens_repbase_fixed_v2
STAR_DIR: /projects/ps-yeolab5/hsher/Tao_circSTAMP/star_2_7_gencode35

QC_TOOLS_PATH: /home/hsher/projects/QC_tools

JAVA_PATH: /projects/ps-yeolab3/eboyle/software/jdk-18.0.1.1/bin/java
UMICOLLAPSE_PATH: /projects/ps-yeolab3/eboyle/software/UMICollapse/umicollapse.jar